server:
  port: 8081
opentracing:
  jaeger:
    service-name: springboot-client
    enabled: true
    udp-sender:
      host: localhost
      port: 6831

backendBaseUrl: http://localhost:9005

logging:
  level:
    root: INFO
    org.springframework.web.servlet: INFO
    org.springframework.web: DEBUG
    com.davidparry: INFO
